[package]
name = "librsync_oxide"
version = "0.3.0"
authors = ["Dropbox Engineering", "bacher09, Artyom Pavlov (RustCrypto/hashes/MD4)"]
license = "Apache-2.0"
description = "An optimized implementation of librsync in pure Rust."
readme = "README.md"
repository = "https://github.com/mriise/librsync_xodie"
keywords = ["rsync"]
edition = "2021"
rust-version = "1.85" 

exclude = [
    ".github",
    ".gitignore",
    "rust-toolchain.toml",
]

[dependencies]
arrayref = "0.3.6"
blake2b_simd = "1.0.5"

[dev-dependencies]
librsync = { version = "0.2.5", default-features = false }
quickcheck = { version = "1.0", default-features = false }
quickcheck_macros = "1.0"
rand = "0.8"
criterion = { version = "0.5", default-features = false }

[[bench]]
name = "rsync_bench"
harness = false
