name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  # make cargo magically go faster
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: rustfmt
      run: cargo fmt --all -- --check
    - name: clippy
      run: cargo clippy --all-targets --locked -- -D warnings
    - name: rustdoc
      run: cargo doc --no-deps --locked
      env:
        RUSTDOCFLAGS: -D warnings

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --all-targets --locked
    - name: Run doctests
      run: cargo test --doc --locked
    - name: Run tests in release mode
      run: cargo test --all-targets --release --locked

  build-i686:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install cross
      run: cargo install cross --git https://github.com/cross-rs/cross
    - name: Run tests (i686)
      run: cross test --all-targets --target i686-unknown-linux-gnu --locked
    - name: Run tests in release mode (i686)
      run: cross test --all-targets --target i686-unknown-linux-gnu --release --locked

  build-aarch64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install cross
      run: cargo install cross --git https://github.com/cross-rs/cross
    - name: Run tests (aarch64)
      run: cross test --all-targets --target aarch64-unknown-linux-gnu --locked
    - name: Run tests in release mode (aarch64)
      run: cross test --all-targets --target aarch64-unknown-linux-gnu --release --locked

  fuzzer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build fuzzer
      run: cd fuzz; cargo test --locked
